### ISSUE TITLE
credentials definition in the schema 

### ISSUE THREAD

**Issue by amirjalali65** [runZeroInc/runzero-api#5]
I'm using generated swagger client in python. Keep getting `AttributeError: 'bool' object has no attribute 'items'` when exporting/retrieving assets and services. The problem was resolved when I filtered for all the attributes except for `credentials`. 
It seems `credentials` definition is wrong in the schema:

```yaml
        credentials:
          type: object
          additionalProperties:
            type: string
            additionalProperties:
              type: boolean

```
`additionalProperties` should have `object` type.
